#+TITLE: Monthly Retrospective: October and November 2022

#+SERIES: ./MonthlyRetrospectives.html
#+SERIES_PREV: ./September2022.html

It is November 19 today, and I’m one month and 4 days late for the
October Retrospective! Truth is, ~$WORK~ has been intense lately, to a
point where I have not made much progress on my side projects. Anyway.

I have implemented the last feature I was really missing in my daily
use of *Spatial Sway*: moving windows to adjacent workspaces. As a
result, I think I can say that Spatial Sway has really reached the
“Minimum Viable Product” stage, with a convenient UX, and a nice
enough UI. It is still lacking when it comes to configurability,
though. It is the next item of my TODO list, but I have no idea when I
will implement the support for a configuration file.

Another highlight of the past two months was the [[https://nanowrimo.org][NaNoWriMo]]. I took the
last week of October and the first week of November off to plan and
start writing a fiction project for it. Writing again was really nice,
and I even gave writing fiction in English a shot. That made me
uncover a bug in the English support of [[https://crates.io/crates/ogam][ogam]], my markup language for
fiction writers, which led me to publish a fix on Crates.io. However,
as soon as I came back to ~$WORK~, my writing spree ended. That’s
Okay, though. It gave me plenty of ideas for future sessions. Thanks,
NaNoWriMo! Sorry to quit so soon, and see you next year, maybe.

Finally, a nice surprise of the past month is that [[https://github.com/ocaml/dune/pull/6489][someone has started
working on adding proper support for ~coqffi~ to ~dune~]], the build
system for OCaml and Coq! I’m thrilled by this. Thanks, [[https://github.com/Alizter][*@Alizter*]]!

This wraps-up this retrospective. I hope I will have more interesting,
concrete news to share next month.
