Welcome to my little corner of the Internet.

You will find it dusty more often than not, but it’s been there for
quite a while now, and its contents might be of interest for you. If
that is the case, I’m thrilled, or I would be if I knew[fn::Please,
let me know!].

* Last Contents
  All categories combined, here is the last pieces of contents I have
  published on this website.

  - [[./opinions/StackedGitPatchTheory.org][Patch Dependencies for Stacked Git]] /(January 25, 2023)/
  - [[./opinions/StackedGit2.org][How I Keep Using Stacked Git at ~$WORK~ in 2023]] /(January 15, 2023)/
  - [[./news/November2022.org][Monthly Retrospective: October and November 2022]] /(November 19, 2022)/
  - [[./news/September2022.org][Monthly Retrospective: September 2022]] /(September 18, 2022)/
  - [[./news/August2022.org][Monthly Retrospective: August 2022]] /(August 15, 2022)/

  I had an RSS feed once, but it’s long gone, mostly because the
  toolchain I ended up writing for generating this website does not
  allow me to generate one easily. I hope it might come back at some
  point.

* Projects
  Here is a curated list of the free software projects I have most
  enjoyed writing, and that made an impact on my daily life.

  - [[https://src.soap.coffee/crates/ogam.git/about][ogam]] is a domain-specific markup language intended to free fiction
    writers from the pain to enforce typographic rules themselves.
  - [[https://sr.ht/~lthms/keyr][*keyr*]] is a collection of software to know how many keystrokes you
    have made since you have started using it.
  - [[https://github.com/coq-community/coqffi][~coqffi~]] is a tool that generates the necessary boilerplate to use
    OCaml functions in a Coq development, and configure the Coq
    extraction mechanism accordingly.
  - [[https://github.com/lthms/spatial-sway][Spatial Sway]] is a daemon that enables a dynamic tiling management
    workflow a la Material Shell and PaperWM.
