#+TITLE: Thanks!

#+SERIES: ./meta.html
#+SERIES_NEXT: ./cleopatra.html

This website could not exist without many awesome free software
projects. Although I could not list them all even if I wanted, my
desire is at least to try keeping up-to-date a curated description of
the most significant ones.

#+BEGIN_EXPORT html
<nav id="generate-toc"></nav>
<div id="history">site/posts/Thanks.org</div>
#+END_EXPORT

* Authoring Content

- [[https://www.gnu.org/software/emacs][Emacs]] ::
  Emacs is an extensible editor which I use daily to author this website
  content, and write the code related to this website (and any code, really). It
  is part of the [[https://www.gnu.org/gnu/gnu.html][GNU project]].
- [[https://orgmode.org/][Org mode]] ::
  Org mode is a major mode of Emacs which I use to author several posts. It has
  initially been written by [[https://staff.science.uva.nl/~dominik/][Carsten Dominik]], and is currently maintained by
  [[http://bzg.fr/][Bastien Guerry]].
- [[https://coq.inria.fr/][Coq]] ::
  Coq is a theorem prover and a proof assistant built by [[https://www.inria.fr/fr][Inria]]. Many of my posts
  on Coq are regular Coq file processed by ~coqdoc~.

* Static Website Generation

- [[https://soupault.app][soupault]] ::
  Soupault is a static website generator and HTML processor written by [[https://www.baturin.org/][Daniil
  Baturin]].

* Frontend

- [[https://katex.org][\im \KaTeX \mi]] ::
  \im \KaTeX \mi is the “fastest” math typesetting library for the web, and is
  used to render inline mathematics in my posts at build time. It has been
  created by [[https://github.com/xymostech][Emily Eisenberg]] and
  [[https://sophiebits.com/][Sophie Alpert]], with the help of
  [[https://github.com/KaTeX/KaTeX/graphs/contributors][many contributors]].
